Repository RHVoice/RHVoice, pull requests merged in 2020-08, with the labels that each got.

#135 Implemented CMake building for Linux components
  .gitignore
  CMakeLists.txt
  cmake/CheckSpdVersion.cmake
  cmake/Hardening.cmake
  cmake/VersionFromGit.cmake
  config/CMakeLists.txt
  data/CMakeLists.txt
  data/languages/CMakeLists.txt
  data/voices/CMakeLists.txt
  src/CMakeLists.txt
  src/audio/CMakeLists.txt
  src/audio/file_playback_stream_impl.cpp
  src/audio/file_playback_stream_impl.hpp
  src/audio/libao.cpp
  src/audio/playback_stream_impl.hpp
  src/audio/portaudio.cpp
  src/audio/pulse.cpp
  src/bin/CMakeLists.txt
  src/config.h.in
  src/core/CMakeLists.txt
  src/core/brazilian_portuguese.cpp
  src/core/config.h
  src/core/config.h.in
  src/core/engine.cpp
  src/core/russian.cpp
  src/include/audio.hpp
  src/include/core/config.hpp
  src/include/core/sample_rate.hpp
  src/lib/CMakeLists.txt
  src/sd_module/CMakeLists.txt
  src/service/CMakeLists.txt
  src/service/service.cpp
  src/test/CMakeLists.txt
  src/test/test.cpp
  src/third-party/CMakeLists.txt
  src/third-party/hts_engine/CMakeLists.txt
  src/third-party/mage/CMakeLists.txt
  src/third-party/sonic/CMakeLists.txt
  src/utils/CMakeLists.txt
Labels: (P3 - Medium), <Enhancement / Feature>, Code: Build, Code: Infrastructure / Style / Static Analysis, OS: Linux, Other, Quality of Life

#164 translate the configuration file into English
  config/RHVoice.conf
Labels: (P2 - High), <Documentation>, <Enhancement / Feature>, Quality of Life

#182 Add new russian male voice
  data/voices/artemiy/16000/bap.pdf
  data/voices/artemiy/16000/bap.win1
  data/voices/artemiy/16000/bap.win2
  data/voices/artemiy/16000/bap.win3
  data/voices/artemiy/16000/bpf.txt
  data/voices/artemiy/16000/dur.pdf
  data/voices/artemiy/16000/lf0.pdf
  data/voices/artemiy/16000/lf0.win1
  data/voices/artemiy/16000/lf0.win2
  data/voices/artemiy/16000/lf0.win3
  data/voices/artemiy/16000/mgc.pdf
  data/voices/artemiy/16000/mgc.win1
  data/voices/artemiy/16000/mgc.win2
  data/voices/artemiy/16000/mgc.win3
  data/voices/artemiy/16000/tree-bap.inf
  data/voices/artemiy/16000/tree-dur.inf
  data/voices/artemiy/16000/tree-lf0.inf
  data/voices/artemiy/16000/tree-mgc.inf
  data/voices/artemiy/16000/voice.data
  data/voices/artemiy/24000/bap.pdf
  data/voices/artemiy/24000/bap.win1
  data/voices/artemiy/24000/bap.win2
  data/voices/artemiy/24000/bap.win3
  data/voices/artemiy/24000/bpf.txt
  data/voices/artemiy/24000/dur.pdf
  data/voices/artemiy/24000/lf0.pdf
  data/voices/artemiy/24000/lf0.win1
  data/voices/artemiy/24000/lf0.win2
  data/voices/artemiy/24000/lf0.win3
  data/voices/artemiy/24000/mgc.pdf
  data/voices/artemiy/24000/mgc.win1
  data/voices/artemiy/24000/mgc.win2
  data/voices/artemiy/24000/mgc.win3
  data/voices/artemiy/24000/tree-bap.inf
  data/voices/artemiy/24000/tree-dur.inf
  data/voices/artemiy/24000/tree-lf0.inf
  data/voices/artemiy/24000/tree-mgc.inf
  data/voices/artemiy/24000/voice.data
  data/voices/artemiy/Readme-en.txt
  data/voices/artemiy/Readme-ru.txt
  data/voices/artemiy/voice.info
  data/voices/artemiy/voice.params
Labels: (P3 - Medium), Data: Voices
