Repository RHVoice/RHVoice, pull requests merged in 2020-06, with the labels that each got.

#122 Add 'targetcross' CSons variable
  SConstruct
Labels: (P3 - Medium), <Enhancement / Feature>, Code: Build

#146 Updating RapidXML in order to fix issues seen in Clang 11
  SConstruct
  src/third-party/rapidxml/rapidxml/rapidxml_iterators.hpp
Labels: (P2 - High), Code: Build, Code: C++, Code: Infrastructure / Style / Static Analysis

#149 Exiting from loop instead of return
  src/core/mage_hts_engine_impl.cpp
Labels: (P3 - Medium), Code: C++, Code: Infrastructure / Style / Static Analysis

#155 Revert "Add 'targetcross' CSons variable"
  SConstruct
Labels: (P1 - Critical), <Bug>, Code: Build

#147 Replacing auto_ptr with shared_ptr, fixing several invalid usecases
  src/android/RHVoice-core/src/main/jni/native.cpp
  src/audio/SConscript
  src/audio/audio.cpp
  src/audio/playback_stream.cpp
  src/core/document.cpp
  src/core/emoji.cpp
  src/core/userdict.cpp
  src/include/audio.hpp
  src/include/core/brazilian_portuguese.hpp
  src/include/core/document.hpp
  src/include/core/dtree.hpp
  src/include/core/emoji.hpp
  src/include/core/ini_parser.hpp
  src/include/core/language.hpp
  src/include/core/mage_hts_engine_impl.hpp
  src/include/core/rules.hpp
  src/include/core/russian.hpp
  src/include/core/std_hts_engine_impl.hpp
  src/include/core/trie.hpp
  src/include/core/userdict.hpp
  src/lib/lib.cpp
  src/sd_module/speech_synthesizer.cpp
  src/service/service.cpp
  src/test/test.cpp
  src/utils/make-hts-labels.cpp
  src/utils/transcribe-sentences.cpp
Labels: (P2 - High), Code: C++, Code: Infrastructure / Style / Static Analysis

#148 Fixing uninitialized values spotted by Valgrind in MAGE::Mage::reset
  src/third-party/mage/mage.cpp
Labels: Code: C++, Code: Infrastructure / Style / Static Analysis

#153 Fixing a warning about hidden virtual function
  src/include/core/voice.hpp
Labels: (P3 - Medium), Code: C++, Code: Infrastructure / Style / Static Analysis

#152 Fixing "initialized after" warnings
  src/core/document.cpp
  src/core/engine.cpp
  src/core/hts_engine_impl.cpp
  src/core/hts_labeller.cpp
  src/core/language.cpp
  src/core/speech_stream.cpp
  src/core/ukrainian.cpp
  src/include/core/document.hpp
  src/include/core/engine.hpp
  src/include/core/quality_setting.hpp
  src/include/core/voice.hpp
Labels: (P2 - High), Code: C++, Code: Infrastructure / Style / Static Analysis

#156 Fixing interruptions of PortAudio-based voice synthesis due to false-failures
  src/audio/portaudio.cpp
  src/include/audio.hpp
  src/test/test.cpp
Labels: (P2 - High), Code: C++, OS: Linux
